FROM node:10
WORKDIR /app
ENV PORT=7500
ENV MONGODB_HOST=ds235078.mlab.com
ENV MONGODB_USER=mohammed
ENV MONGODB_PASSWORD=mohBaba1
ENV MONGODB_PORT=35078
ENV BASE_URL=
ENV MONGODB_DATABASE_NAME=oda
ENV JWT_SECRET_KEY=dfnidijknr9ru48rvhersfoersfjo
ENV CLOUDINARY_NAME=benzowe
ENV CLOUDINARY_API_KEY=337272163555388
ENV CLOUDINARY_API_SECRET=PJLscpHGj1FDUwM3JKhhlDJgo90
ENV AWS_ACCESS_KEY_ID=AKIAYJ3WSSSC45UAJBL5
ENV AWS_SECRET_ACCESS_KEY=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
ENV AWS_BUCKET=rekognition-vision-images
ENV AWS_REGION=us-east-1%
COPY package.json .
RUN npm install
COPY . .
EXPOSE 7500
CMD ["npm", "start"]
